### ISSUE TITLE
error when searching for product (product_finder.js)

### ISSUE THREAD

**Issue by nghiatrongnguyen** [domanhdoan/auto-sale#39]
Unhandled rejection ReferenceError: session is not defined
    at C:\Users\Administrator\Projects\auto-sale\controllers\shoes_saleman_fbbot_aiapi.js:741:29
    at C:\Users\Administrator\Projects\auto-sale\controllers\product_finder.js:135:21
    at tryCatcher (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:499:35)
    at Promise._settlePromise (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:628:18)
    at PromiseArray._resolve (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise_array.js:143:14)
    at PromiseArray._iterate (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise_array.js:113:31)
    at PromiseArray.init [as _init](C:UsersAdministratorProjectsauto-salenode_modulessequelizenode_modulesbluebirdjsreleasepromise_array.js:77:10)
    at Promise._settlePromise (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:556:21)
    at Promise._settlePromise0 (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (C:\Users\Administrator\Projects\auto-sale\node_modules\sequelize\node_modules\bluebird\js\release\async.js:138:16)

**Comment by domanhdoan** [comment]
this issue fixed (just adding code to cut all special character of Vietnamese) @nghiatrongnguyen
